name: Renovate Updates
on:
  workflow_dispatch: {}
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Renovate
        uses: renovatebot/github-action@v43.0.1
        env:
            RENOVATE_GPR_TOKEN: ${{ secrets.GPR_TOKEN }}
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}